# This is a basic workflow to help you get started with Actions

name: Build spindrift pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-spindrift:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout spindrift
        run: |
          git clone https://github.com/zthart/spindrift.git
          cd spindrift
          export SPINDRIFT_WORKSPACE=$(pwd)

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build spindrift
        run: |
          cd $SPINDRIFT_WORKSPACE
          cargo build --release
          cd target/release
          export SPINDRIFT_BIN_DIR=$(pwd)
    
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run spindrift
        run: |
          cd $GITHUB_WORKSPACE
          $SPINDIRFT_BIN_DIR/spindrift -t _spindrift_templates -c _spindrift.yaml -s _posts -o static
          
  commit-droplets:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git config
        run: |
          git config user.name "Spindrift Runner"
          git config user.email "<>"

      - name: commit added files
        run: |
          git add static/*
          git commit -m "Build spindrift pages"
          git push origin master
