# This is a basic workflow to help you get started with Actions

name: Build spindrift pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Checkout spindrift
        run: |
          git clone https://github.com/zthart/spindrift.git
          cd spindrift
          export SPINDRIFT_WORKSPACE=$(pwd)
      
      # Build spindrift
      - name: Build spindrift
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --release

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd $GITHUB_WORKSPACE
          $SPINDRIFT_WORKSPACE/target/release/spindrift -t _spindrift_templates -c _spindrift.yaml -s _posts -o static
